### ISSUE TITLE
Set up questions and answer possibilities

### ISSUE THREAD

**Issue by carolinwagner** [carolinwagner/capstone-project#1]
## Value statement 
As a club founder
I need bylaws for my club (required by law). I want to answer simple questions
so that I can get individual bylaws for my club. 

## Description (Text, Scribble, Wireframe, Design)
![Image from iOS (10)](https://user-images.githubusercontent.com/34626937/92300837-6e9d7a80-ef5e-11ea-8a6a-6a1a5442bfeb.jpg)
![Image from iOS (11)](https://user-images.githubusercontent.com/34626937/92300841-7b21d300-ef5e-11ea-969f-0545265e1308.jpg)
![Image from iOS (12)](https://user-images.githubusercontent.com/34626937/92300847-8a088580-ef5e-11ea-9451-3b9d183ff4cf.jpg)
![Image from iOS (13)](https://user-images.githubusercontent.com/34626937/92300851-91c82a00-ef5e-11ea-9a53-1b47781bc70c.jpg)

## Acceptance criteria
- [x] User can answer all questions / by clicking or using inputs (no validation of inputs)
- [x] User can get an overview of his answers by clicking "Zusammenfassung" 

## Tasks
- [x] create feature branch
- [x] initialize react-app
- [x] remove unnecessary template files
- [x] research suitable questions and answers for creating bylaws 
- [x] create header
- [x] add questions as json file
- [x] create questions
- [x] create answer possibilities and inputs
- [x] show inputs/answers when button "Zusammenfassung" is clicked
- [x] add GlobalStyles
- [x] add components in storybook
- [x] unit testing

## Size
Medium/Large
