### ISSUE TITLE
Each question on single page

### ISSUE THREAD

**Issue by carolinwagner** [carolinwagner/capstone-project#12]
## Value statement - a requirement, not a solution
As a user
I want to have only one question on one page
so that I can concentrate on one question.

## Description (Text, Scribble, Wireframe, Design)

![Bylaws-2020-09-22](https://user-images.githubusercontent.com/34626937/93864727-96624180-fcc5-11ea-9ab2-8f431279a13e.png)

## Acceptance criteria
- [x] user can see one question on one page
- [x] user can click on forward button to get to the next question
- [x] user can click on backward button to get to the previous question
- [x] first question page has button which leads to start page
- [x] last question page has button which leads to bylaws text page
- [x] bylaws text is shown when all questions are answered and user clicks on "Satzung anzeigen" button on last question page

## Tasks
- [x] One question on one page
- [x] Add forwards button
- [x] Add backwards button
- [x] Save user's answers in bylawstext
- [x] Update cypress tests

## Size
large

**Comment by maximiliangustmann** [comment]
- Wenn ich versuche mit enter zu submitten, gelange ich zurück zur ersten Seite.
- Wenn ich auf zurück klicke, sind meine vorherigen Antworten gelöscht. Hier wäre es schön zu sehen, was ich bereits eingetragen/ausgewählt habe. 
- Es wäre noch gut, bei den Fragen ein freies Textfeld einzufügen. Es kann immer mal sein, dass die vorgegebenen Antworten nicht passen und dann hängt der User in deiner App fest.
