### ISSUE TITLE
Three Pages: Start, Questions, Bylaws

### ISSUE THREAD

**Issue by carolinwagner** [carolinwagner/capstone-project#13]
## Value statement - a requirement, not a solution
As a user
I need a start page, a question page and a bylaws page
so that I know what to do, answer questions and see the bylaws separated.

## Description (Text, Scribble, Wireframe, Design)
![Bylaws-2020-09-18](https://user-images.githubusercontent.com/34626937/93354408-3f7be880-f83d-11ea-8e68-0b37cd1d6e65.png)

## Acceptance criteria
- [x] user can click a button on the start page (path: /) to start the questions
- [x] user can click a button on the questions page (path: /questions) to go to the generated bylaws 
- [x] user can click a button on the bylaws text page (path: /bylawstext) to go back to the questions 

## Tasks
- [x] create feature branch
- [x] add Router
- [x] path '/start' for start page
- [x] path '/questionnaire' for questionnaire page
- [x] path '/bylawstext' for bylaws text page
- [x] start-button
- [x] bylaws-button
- [x] back to questions-button
- [x] update cypress tests
- [x] add cypress tests for start and bylaws text page

## Size
medium
