### ISSUE TITLE
"More information" button

### ISSUE THREAD

**Issue by carolinwagner** [carolinwagner/capstone-project#17]
## Value statement - a requirement, not a solution
As a user 
I need more information 
so that I know how to answer the question best.

## Description (Text, Scribble, Wireframe, Design)
<img width="693" alt="Screenshot 2020-09-23 at 12 39 17" src="https://user-images.githubusercontent.com/34626937/94002481-3d181200-fd9a-11ea-8553-c492046680a5.png">

## Acceptance criteria
- [x] user can click "Mehr Infos" button and see more information corresponding to the question
- [x] user can click "Weniger Infos" button and hide the information

## Tasks
- [x] research legal information corresponding to the question
- [x] add button
- [x] add toggle logic
- [x] adjust styling 

## Size
large
