### ISSUE TITLE
Generate bylaws text

### ISSUE THREAD

**Issue by carolinwagner** [carolinwagner/capstone-project#2]
## Value statement 
As a user
I need to see the generated bylaws
so that I can reuse them.

## Description (Text, Scribble, Wireframe, Design)

![HelloBylawsSetUp 2020-09-13](https://user-images.githubusercontent.com/34626937/93026933-f4c65a80-f609-11ea-99c4-bc277b05443e.png)

## Acceptance criteria
- [x] User can see the created bylaws with his individual input

## Tasks
- [x] change button "Zusammenfassung anzeigen" into "Satzung anzeigen"
- [x] research suitable bylaws template
- [x] generate bylaws with the user's input
- [x] show generated bylaws on the same page  
- [x] update cypress tests

## Size
large

**Comment by annidrumm** [comment]
QA:
- Button shows the users input correctly.
- I think the light blue fits your app really well! You could maybe think about a little darker shade for the button, to underline that this is an action button. Light colors tend to show disabled buttons.
Overall very well made so far 👍

**Comment by carolinwagner** [comment]
Thanks a lot, @annidrumm :-) I will experiment with the button's color in my next story!
