### ISSUE TITLE
Download generated bylaws as text

### ISSUE THREAD

**Issue by carolinwagner** [carolinwagner/capstone-project#20]
## Value statement - a requirement, not a solution
As a user
I need to download the generated bylaws
so that I can save them easily.

## Description (Text, Scribble, Wireframe, Design)
<img width="323" alt="Screenshot 2020-09-28 at 12 04 12" src="https://user-images.githubusercontent.com/34626937/94419244-c22c6e00-0182-11eb-8334-97e3dd62eaa8.png">

## Acceptance criteria
- [x] user can download generated bylaws as txt
- [x] button text changes when user clicked button

## Tasks
- [x] create feature branch
- [x] add download button
- [x] add download logic

## Size
medium
