### ISSUE TITLE
Copy generated bylaws

### ISSUE THREAD

**Issue by carolinwagner** [carolinwagner/capstone-project#3]
## Value statement
As a user
I need to copy the generated bylaws
so that I can reuse them easily.

## Description (Text, Scribble, Wireframe, Design)
![Bylaws-2020-09-22_copyButton](https://user-images.githubusercontent.com/34626937/93871103-6a978980-fcce-11ea-976d-ef5d3dc6618e.png)

## Acceptance criteria
- [x] User can copy bylaws
- [x] Show ✅ in "Satzungstext kopieren" button, when Bylaws are copied to clipboard

## Tasks
- [x] Add button "Satzungstext kopieren"
- [x] Add copy function
- [x] Add ✅ in "Satzungstext kopieren" button, when Bylaws are copied to clipboard
- [x] Update cypress test

## Size
medium
