### ISSUE TITLE
Form Validation

### ISSUE THREAD

**Issue by carolinwagner** [carolinwagner/capstone-project#6]
## Value statement - a requirement, not a solution
As a user
I need to be forced to answer all questions within the correct formal criteria 
so that my bylaws will come out precisely

## Description (Text, Scribble, Wireframe, Design)
![HelloBylawsValidation 2020-09-08](https://user-images.githubusercontent.com/34626937/92460493-516be480-f1c8-11ea-992b-16e1ff925a03.png)

## Acceptance criteria
- [x] error message if an answer is missing completely 
- [x] no number inputs < 1 possible
- [x] number in question no. 23 must be min. 7 (due to min. number of founding members)
- [x] numbers in question no. 9 and 18 must be min. 14 
- [x] date (question no. 22) must be min. today's date
- [x] if question is answered after error message: error message will disappear with a click on the "Zusammenfassung anzeigen" button

## Tasks
- [x] create feature branch
- [x] validation and error message for text inputs
- [x] min. values for number inputs 
- [x] validation for date input (min date must be today's date)
- [x] validation and error message for number inputs
- [x] validation and error message for checkbox inputs
- [x] validation error message for radio inputs

## Size
medium
